version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/addisonhuddy/kfuse
