// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api/events.proto

package kfusev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope is the Kafka record value. Records carry only metadata and
// blob references; file bytes live in S3. Reads are never logged.
type EventEnvelope struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Seq        uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // per-session, writer-assigned, monotonic from 1
	UnixMicros int64                  `protobuf:"varint,2,opt,name=unix_micros,json=unixMicros,proto3" json:"unix_micros,omitempty"`
	SessionId  string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LowerId    string                 `protobuf:"bytes,4,opt,name=lower_id,json=lowerId,proto3" json:"lower_id,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*EventEnvelope_SessionStart
	//	*EventEnvelope_Create
	//	*EventEnvelope_Write
	//	*EventEnvelope_Unlink
	//	*EventEnvelope_Rmdir
	//	*EventEnvelope_Mkdir
	//	*EventEnvelope_Rename
	//	*EventEnvelope_Symlink
	//	*EventEnvelope_Setattr
	Op            isEventEnvelope_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_api_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventEnvelope) GetUnixMicros() int64 {
	if x != nil {
		return x.UnixMicros
	}
	return 0
}

func (x *EventEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventEnvelope) GetLowerId() string {
	if x != nil {
		return x.LowerId
	}
	return ""
}

func (x *EventEnvelope) GetOp() isEventEnvelope_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *EventEnvelope) GetSessionStart() *SessionStart {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *EventEnvelope) GetCreate() *Create {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *EventEnvelope) GetWrite() *Write {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *EventEnvelope) GetUnlink() *Unlink {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Unlink); ok {
			return x.Unlink
		}
	}
	return nil
}

func (x *EventEnvelope) GetRmdir() *Rmdir {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Rmdir); ok {
			return x.Rmdir
		}
	}
	return nil
}

func (x *EventEnvelope) GetMkdir() *Mkdir {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *EventEnvelope) GetRename() *Rename {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *EventEnvelope) GetSymlink() *Symlink {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Symlink); ok {
			return x.Symlink
		}
	}
	return nil
}

func (x *EventEnvelope) GetSetattr() *Setattr {
	if x != nil {
		if x, ok := x.Op.(*EventEnvelope_Setattr); ok {
			return x.Setattr
		}
	}
	return nil
}

type isEventEnvelope_Op interface {
	isEventEnvelope_Op()
}

type EventEnvelope_SessionStart struct {
	SessionStart *SessionStart `protobuf:"bytes,10,opt,name=session_start,json=sessionStart,proto3,oneof"`
}

type EventEnvelope_Create struct {
	Create *Create `protobuf:"bytes,11,opt,name=create,proto3,oneof"`
}

type EventEnvelope_Write struct {
	Write *Write `protobuf:"bytes,12,opt,name=write,proto3,oneof"`
}

type EventEnvelope_Unlink struct {
	Unlink *Unlink `protobuf:"bytes,13,opt,name=unlink,proto3,oneof"`
}

type EventEnvelope_Rmdir struct {
	Rmdir *Rmdir `protobuf:"bytes,14,opt,name=rmdir,proto3,oneof"`
}

type EventEnvelope_Mkdir struct {
	Mkdir *Mkdir `protobuf:"bytes,15,opt,name=mkdir,proto3,oneof"`
}

type EventEnvelope_Rename struct {
	Rename *Rename `protobuf:"bytes,16,opt,name=rename,proto3,oneof"`
}

type EventEnvelope_Symlink struct {
	Symlink *Symlink `protobuf:"bytes,17,opt,name=symlink,proto3,oneof"`
}

type EventEnvelope_Setattr struct {
	Setattr *Setattr `protobuf:"bytes,18,opt,name=setattr,proto3,oneof"`
}

func (*EventEnvelope_SessionStart) isEventEnvelope_Op() {}

func (*EventEnvelope_Create) isEventEnvelope_Op() {}

func (*EventEnvelope_Write) isEventEnvelope_Op() {}

func (*EventEnvelope_Unlink) isEventEnvelope_Op() {}

func (*EventEnvelope_Rmdir) isEventEnvelope_Op() {}

func (*EventEnvelope_Mkdir) isEventEnvelope_Op() {}

func (*EventEnvelope_Rename) isEventEnvelope_Op() {}

func (*EventEnvelope_Symlink) isEventEnvelope_Op() {}

func (*EventEnvelope_Setattr) isEventEnvelope_Op() {}

type SessionStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerId       string                 `protobuf:"bytes,1,opt,name=lower_id,json=lowerId,proto3" json:"lower_id,omitempty"`
	Lineage       *Lineage               `protobuf:"bytes,2,opt,name=lineage,proto3" json:"lineage,omitempty"` // empty for a root (new) session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_api_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStart) GetLowerId() string {
	if x != nil {
		return x.LowerId
	}
	return ""
}

func (x *SessionStart) GetLineage() *Lineage {
	if x != nil {
		return x.Lineage
	}
	return nil
}

type Lineage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentSessionId string                 `protobuf:"bytes,1,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	ParentOffset    int64                  `protobuf:"varint,2,opt,name=parent_offset,json=parentOffset,proto3" json:"parent_offset,omitempty"` // inclusive end of parent prefix (= B)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lineage) Reset() {
	*x = Lineage{}
	mi := &file_api_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lineage) ProtoMessage() {}

func (x *Lineage) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lineage.ProtoReflect.Descriptor instead.
func (*Lineage) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{2}
}

func (x *Lineage) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *Lineage) GetParentOffset() int64 {
	if x != nil {
		return x.ParentOffset
	}
	return 0
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // relative to lower root, cleaned, '/'-sep, no leading '/'
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BlobId        []byte                 `protobuf:"bytes,4,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"` // sha256 of the blob object
	BlobOffset    uint64                 `protobuf:"varint,5,opt,name=blob_offset,json=blobOffset,proto3" json:"blob_offset,omitempty"`
	Eof           bool                   `protobuf:"varint,6,opt,name=eof,proto3" json:"eof,omitempty"`                 // true => truncate file to (offset+length) after this write
	Mode          uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`               // used only when this Write creates the file
	Fallthrough   bool                   `protobuf:"varint,8,opt,name=fallthrough,proto3" json:"fallthrough,omitempty"` // true when this Write creates a node over a lower file (sparse CoW)
	Uid           uint32                 `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`                 // carried when materializing a lower-backed file (sparse CoW)
	Gid           uint32                 `protobuf:"varint,10,opt,name=gid,proto3" json:"gid,omitempty"`                // carried when materializing a lower-backed file (sparse CoW)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_api_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{3}
}

func (x *Write) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Write) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Write) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Write) GetBlobId() []byte {
	if x != nil {
		return x.BlobId
	}
	return nil
}

func (x *Write) GetBlobOffset() uint64 {
	if x != nil {
		return x.BlobOffset
	}
	return 0
}

func (x *Write) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *Write) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Write) GetFallthrough() bool {
	if x != nil {
		return x.Fallthrough
	}
	return false
}

func (x *Write) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Write) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_api_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{4}
}

func (x *Create) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Create) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Create) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Create) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Mkdir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mkdir) Reset() {
	*x = Mkdir{}
	mi := &file_api_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mkdir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mkdir) ProtoMessage() {}

func (x *Mkdir) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mkdir.ProtoReflect.Descriptor instead.
func (*Mkdir) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{5}
}

func (x *Mkdir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Mkdir) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Mkdir) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Mkdir) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Symlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symlink) Reset() {
	*x = Symlink{}
	mi := &file_api_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symlink) ProtoMessage() {}

func (x *Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symlink.ProtoReflect.Descriptor instead.
func (*Symlink) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{6}
}

func (x *Symlink) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Symlink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Symlink) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Symlink) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Unlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlink) Reset() {
	*x = Unlink{}
	mi := &file_api_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlink) ProtoMessage() {}

func (x *Unlink) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlink.ProtoReflect.Descriptor instead.
func (*Unlink) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{7}
}

func (x *Unlink) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Rmdir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rmdir) Reset() {
	*x = Rmdir{}
	mi := &file_api_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rmdir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rmdir) ProtoMessage() {}

func (x *Rmdir) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rmdir.ProtoReflect.Descriptor instead.
func (*Rmdir) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{8}
}

func (x *Rmdir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Rename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	FromLower     bool                   `protobuf:"varint,3,opt,name=from_lower,json=fromLower,proto3" json:"from_lower,omitempty"` // true if `from` existed in the lower tree (whiteout it)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rename) Reset() {
	*x = Rename{}
	mi := &file_api_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rename) ProtoMessage() {}

func (x *Rename) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rename.ProtoReflect.Descriptor instead.
func (*Rename) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{9}
}

func (x *Rename) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Rename) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Rename) GetFromLower() bool {
	if x != nil {
		return x.FromLower
	}
	return false
}

type Setattr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          *uint32                `protobuf:"varint,2,opt,name=mode,proto3,oneof" json:"mode,omitempty"`
	Uid           *uint32                `protobuf:"varint,3,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	Gid           *uint32                `protobuf:"varint,4,opt,name=gid,proto3,oneof" json:"gid,omitempty"`
	AtimeNs       *int64                 `protobuf:"varint,5,opt,name=atime_ns,json=atimeNs,proto3,oneof" json:"atime_ns,omitempty"`
	MtimeNs       *int64                 `protobuf:"varint,6,opt,name=mtime_ns,json=mtimeNs,proto3,oneof" json:"mtime_ns,omitempty"`
	Size          *uint64                `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"` // truncate (up or down)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setattr) Reset() {
	*x = Setattr{}
	mi := &file_api_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setattr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setattr) ProtoMessage() {}

func (x *Setattr) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setattr.ProtoReflect.Descriptor instead.
func (*Setattr) Descriptor() ([]byte, []int) {
	return file_api_events_proto_rawDescGZIP(), []int{10}
}

func (x *Setattr) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Setattr) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

func (x *Setattr) GetUid() uint32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *Setattr) GetGid() uint32 {
	if x != nil && x.Gid != nil {
		return *x.Gid
	}
	return 0
}

func (x *Setattr) GetAtimeNs() int64 {
	if x != nil && x.AtimeNs != nil {
		return *x.AtimeNs
	}
	return 0
}

func (x *Setattr) GetMtimeNs() int64 {
	if x != nil && x.MtimeNs != nil {
		return *x.MtimeNs
	}
	return 0
}

func (x *Setattr) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_api_events_proto protoreflect.FileDescriptor

const file_api_events_proto_rawDesc = "" +
	"\n" +
	"\x10api/events.proto\x12\bkfuse.v1\"\x9e\x04\n" +
	"\rEventEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1f\n" +
	"\vunix_micros\x18\x02 \x01(\x03R\n" +
	"unixMicros\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\blower_id\x18\x04 \x01(\tR\alowerId\x12=\n" +
	"\rsession_start\x18\n" +
	" \x01(\v2\x16.kfuse.v1.SessionStartH\x00R\fsessionStart\x12*\n" +
	"\x06create\x18\v \x01(\v2\x10.kfuse.v1.CreateH\x00R\x06create\x12'\n" +
	"\x05write\x18\f \x01(\v2\x0f.kfuse.v1.WriteH\x00R\x05write\x12*\n" +
	"\x06unlink\x18\r \x01(\v2\x10.kfuse.v1.UnlinkH\x00R\x06unlink\x12'\n" +
	"\x05rmdir\x18\x0e \x01(\v2\x0f.kfuse.v1.RmdirH\x00R\x05rmdir\x12'\n" +
	"\x05mkdir\x18\x0f \x01(\v2\x0f.kfuse.v1.MkdirH\x00R\x05mkdir\x12*\n" +
	"\x06rename\x18\x10 \x01(\v2\x10.kfuse.v1.RenameH\x00R\x06rename\x12-\n" +
	"\asymlink\x18\x11 \x01(\v2\x11.kfuse.v1.SymlinkH\x00R\asymlink\x12-\n" +
	"\asetattr\x18\x12 \x01(\v2\x11.kfuse.v1.SetattrH\x00R\asetattrB\x04\n" +
	"\x02op\"V\n" +
	"\fSessionStart\x12\x19\n" +
	"\blower_id\x18\x01 \x01(\tR\alowerId\x12+\n" +
	"\alineage\x18\x02 \x01(\v2\x11.kfuse.v1.LineageR\alineage\"Z\n" +
	"\aLineage\x12*\n" +
	"\x11parent_session_id\x18\x01 \x01(\tR\x0fparentSessionId\x12#\n" +
	"\rparent_offset\x18\x02 \x01(\x03R\fparentOffset\"\xf1\x01\n" +
	"\x05Write\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x17\n" +
	"\ablob_id\x18\x04 \x01(\fR\x06blobId\x12\x1f\n" +
	"\vblob_offset\x18\x05 \x01(\x04R\n" +
	"blobOffset\x12\x10\n" +
	"\x03eof\x18\x06 \x01(\bR\x03eof\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\x12 \n" +
	"\vfallthrough\x18\b \x01(\bR\vfallthrough\x12\x10\n" +
	"\x03uid\x18\t \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\n" +
	" \x01(\rR\x03gid\"T\n" +
	"\x06Create\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\"S\n" +
	"\x05Mkdir\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\"Y\n" +
	"\aSymlink\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\"\x1c\n" +
	"\x06Unlink\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1b\n" +
	"\x05Rmdir\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"K\n" +
	"\x06Rename\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"from_lower\x18\x03 \x01(\bR\tfromLower\"\xf9\x01\n" +
	"\aSetattr\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\x04mode\x18\x02 \x01(\rH\x00R\x04mode\x88\x01\x01\x12\x15\n" +
	"\x03uid\x18\x03 \x01(\rH\x01R\x03uid\x88\x01\x01\x12\x15\n" +
	"\x03gid\x18\x04 \x01(\rH\x02R\x03gid\x88\x01\x01\x12\x1e\n" +
	"\batime_ns\x18\x05 \x01(\x03H\x03R\aatimeNs\x88\x01\x01\x12\x1e\n" +
	"\bmtime_ns\x18\x06 \x01(\x03H\x04R\amtimeNs\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\a \x01(\x04H\x05R\x04size\x88\x01\x01B\a\n" +
	"\x05_modeB\x06\n" +
	"\x04_uidB\x06\n" +
	"\x04_gidB\v\n" +
	"\t_atime_nsB\v\n" +
	"\t_mtime_nsB\a\n" +
	"\x05_sizeB+Z)github.com/addisonhuddy/kfuse/api/kfusev1b\x06proto3"

var (
	file_api_events_proto_rawDescOnce sync.Once
	file_api_events_proto_rawDescData []byte
)

func file_api_events_proto_rawDescGZIP() []byte {
	file_api_events_proto_rawDescOnce.Do(func() {
		file_api_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_events_proto_rawDesc), len(file_api_events_proto_rawDesc)))
	})
	return file_api_events_proto_rawDescData
}

var file_api_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_events_proto_goTypes = []any{
	(*EventEnvelope)(nil), // 0: kfuse.v1.EventEnvelope
	(*SessionStart)(nil),  // 1: kfuse.v1.SessionStart
	(*Lineage)(nil),       // 2: kfuse.v1.Lineage
	(*Write)(nil),         // 3: kfuse.v1.Write
	(*Create)(nil),        // 4: kfuse.v1.Create
	(*Mkdir)(nil),         // 5: kfuse.v1.Mkdir
	(*Symlink)(nil),       // 6: kfuse.v1.Symlink
	(*Unlink)(nil),        // 7: kfuse.v1.Unlink
	(*Rmdir)(nil),         // 8: kfuse.v1.Rmdir
	(*Rename)(nil),        // 9: kfuse.v1.Rename
	(*Setattr)(nil),       // 10: kfuse.v1.Setattr
}
var file_api_events_proto_depIdxs = []int32{
	1,  // 0: kfuse.v1.EventEnvelope.session_start:type_name -> kfuse.v1.SessionStart
	4,  // 1: kfuse.v1.EventEnvelope.create:type_name -> kfuse.v1.Create
	3,  // 2: kfuse.v1.EventEnvelope.write:type_name -> kfuse.v1.Write
	7,  // 3: kfuse.v1.EventEnvelope.unlink:type_name -> kfuse.v1.Unlink
	8,  // 4: kfuse.v1.EventEnvelope.rmdir:type_name -> kfuse.v1.Rmdir
	5,  // 5: kfuse.v1.EventEnvelope.mkdir:type_name -> kfuse.v1.Mkdir
	9,  // 6: kfuse.v1.EventEnvelope.rename:type_name -> kfuse.v1.Rename
	6,  // 7: kfuse.v1.EventEnvelope.symlink:type_name -> kfuse.v1.Symlink
	10, // 8: kfuse.v1.EventEnvelope.setattr:type_name -> kfuse.v1.Setattr
	2,  // 9: kfuse.v1.SessionStart.lineage:type_name -> kfuse.v1.Lineage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_events_proto_init() }
func file_api_events_proto_init() {
	if File_api_events_proto != nil {
		return
	}
	file_api_events_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_SessionStart)(nil),
		(*EventEnvelope_Create)(nil),
		(*EventEnvelope_Write)(nil),
		(*EventEnvelope_Unlink)(nil),
		(*EventEnvelope_Rmdir)(nil),
		(*EventEnvelope_Mkdir)(nil),
		(*EventEnvelope_Rename)(nil),
		(*EventEnvelope_Symlink)(nil),
		(*EventEnvelope_Setattr)(nil),
	}
	file_api_events_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_events_proto_rawDesc), len(file_api_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_events_proto_goTypes,
		DependencyIndexes: file_api_events_proto_depIdxs,
		MessageInfos:      file_api_events_proto_msgTypes,
	}.Build()
	File_api_events_proto = out.File
	file_api_events_proto_goTypes = nil
	file_api_events_proto_depIdxs = nil
}
