#!/usr/bin/env bash
# Credential-free local stack for the kfuse benchmark suite: Apache Kafka
# (single-node KRaft) + MinIO, shared with examples/local.
#
#   ./examples/perf/local-stack.sh up      start containers, write .stack-env
#   ./examples/perf/local-stack.sh down    stop containers
#
# `up` writes examples/perf/.stack-env; source it before running run.sh.
set -euo pipefail
cd "$(dirname "$0")"

PERF_BUCKET=${KF_PERF_BUCKET:-kfuse-perf}

up() {
  export KF_LOCAL_BUCKET=$PERF_BUCKET
  ../local/up.sh
  {
    echo "# generated by local-stack.sh; do not commit"
    while IFS= read -r line; do
      case "$line" in
        ""|\#*) continue ;;
        S3_BUCKET=*) printf 'export S3_BUCKET=%s\n' "$PERF_BUCKET" ;;
        *) printf 'export %s\n' "$line" ;;
      esac
    done < ../local/local.env
  } > .stack-env
  echo "local-stack: up. Run: source examples/perf/.stack-env"
}

case "${1:-}" in
  up) up ;;
  down) ../local/down.sh; echo "local-stack: down" ;;
  *) echo "usage: local-stack.sh <up|down>"; exit 2 ;;
esac
